version: '3'

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        command: mysqld --sql_mode="" --character-set-server=latin1 --collation-server=latin1_swedish_ci
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./docker/sql/:/docker-entrypoint-initdb.d/

networks:
    bridge:
